# Generated by Django 4.2 on 2023-04-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='owner',
            new_name='ownertest',
        ),
    ]
